name: geometry
description: Geometry Store is an e-commerce app.

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
  
  fonts:
   - family: Work Sans
     fonts:
       - asset: fonts/static/WorkSans-Regular.ttf
       - asset: fonts/static/WorkSans-Bold.ttf
   - family: Source Sans
     fonts:
       - asset: fonts/SourceSansPro-Regular.ttf