name: geometry
description: Geometry Store is an e-commerce app.

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
  
  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Black.ttf
        - asset: fonts/Gilroy-Bold.ttf